---
title: "L1 English L2 Spanish Coronal Stop-Rhotic Cluster Training: An Ultrasound Study"
shorttitle: "Ultrasound: Alveolar to Dental"
author:
  - name: Robert Esposito
    corresponding: true
    email: rme70@rutgers.edu
    affiliations:
      name: "Rutgers University"
      department: Department of Spanish and Portuguese
      address: 15 Seminary Pl.
      city: New Brunswick
      region: NJ
      country: USA
      postal-code: 08901
author-note:
  # Disclosures condensed to one paragraph, but you can start a field with two line breaks to break them up: \n\nNew Paragraph
  disclosures:
    # Example: This study was registered at X (Identifier Y).
    study-registration: ~
    # Acknowledge and cite data/materials to be shared.
    data-sharing: ~
    # Example: This article is based on data published in [Reference].
    # Example: This article is based on the dissertation completed by [citation].  
    related-report: ~
    # Example: [Author name] has been a paid consultant for Corporation X, which funded this study.
    conflict-of-interest: The authors have no conflicts of interest to disclose.
    # Example: This study was supported by Grant [Grant Number] from [Funding Source].
    financial-support: ~
    # Example: The authors are grateful to [Person] for [Reason].
    gratitude: ~
    # Example. Because the authors are equal contributors, order of authorship was determined by a fair coin toss.
    authorship-agreements: ~
number-sections: false
abstract: "THE ABSTRACT GOES HERE."
keywords: [the, keywords, go, here]
floatsintext: true
bibliography: "./lit/l2_esp_alv_to_dent.bib"
format:
  apaquarto-docx: default
  apaquarto-html: default
  apaquarto-pdf:
    documentmode: man
---

```{r}
#| include: false

# load libs
library(here)
```

Second language (L2) learners have the task of acquiring a new phonological system, including language-specific timing and fine-grained phonetic details, after they have already established their first language (L1). Although some researchers have claimed that native-like acquisition of fine-grained phonetics is impossible [@scovel1988power; @long1990least], others have demonstrated that exceptional cases exist in which L2 speakers have performed in a native-like manner [@colantoni2006native; @face2021ultimate]. In the L2 classroom, phonetics receives little attention in general [@derwing2005second; @gilbert2014intonation] despite the fact that both explicit [@gordon2012pronunciation] and implicit [@saito2015communicative] teaching methodologies have resulted in more target-like production.

One methodology for incorporating training of non-native sounds in L2 learners is ultrasound visualization [@kelsey1969applications; @stone2005preface]. Ultrasound has a history of use in clinical settings for diagnosis and rehabilitation [@dugan2023qualitative], and it has been extended to teaching spoken language to the deaf and hard of hearing [@bernhardt2005ultrasound; @bernhardt2003speech] and to L2 learners [@bliss2018computer; @gick2008ultrasound; @wilson2014using; @levitt2007augmented]. The present study is a single-participant design [@gick2008ultrasound] investigating the effects of ultrasound visualization feedback on the acquisition of /t d/ + /ɾ/ clusters in L1 English L2 Spanish learners. Over the course of five weeks in a domestic immersion language program, participants completed a pre-test, three ultrasound training sessions, and a post-test. In each of the five sessions, participants completed a production task, targeting the coronal stop-rhotic clusters, as well as AXB discrimination and AB identification perception tasks to better understand the relationship between production and perception.

## Visual Feedback

Spoken language is transmitted auditorily, but speakers have been found to incorporate visual information in both their first language [@bernstein2004auditory] and their second language [@navarra2007hearing; @engwall2008can]. In the second language (L2) classroom, teachers have taken advantage of multimodality to teach suprasegmentals [@chun2002discourse; @chun1998signal; @chun1989teaching], but little attention has been paid to how multimodality, specifically visual feedback, can supplement the teaching of segmentals [@bliss2018computer]. Indirect visual feedback, such as visualization of acoustic information through spectrography [@molholt1990spectrographic], has resulted in positive gains for learners [@akahane1997second; @olson2014benefits]. However, spectrography, and other indirect feedback methodology, typically has a steep learning curve, does not provide an explanation of the user's error or its causes and may lead to frustration in the learner [@rogerson2021computer; @wilson2014using]. 

In contrast with indirect visualization methods, direct visualization techniques provide users with the position and movements of their articulators during speech. Intra-oral techniques, such as electromagnetic articulography (EMA), have produced gains in learner pronunciation of segments [@levitt2007augmented; @suemitsu2015real], but the technology can prove to be prohibitively expensive for the teacher and uncomfortably intrusive for the learner. In comparison, ultrasound machines have become increasingly affordable, portable and are non-invasive for the learner [@gick2005techniques]. Ultrasound has a history of use in clinical settings [@dugan2023qualitative] and for teaching spoken language to the hard-of-hearing and deaf [@bernhardt2005ultrasound; @bernhardt2003speech] and accent correction in L2 learners [@badin2010visual; @ouni2014tongue]. Despite ultrasound machines' growing affordability, portability, and benefits for L2 learners' segmental pronunciation, they remain rare in both the L2 classroom and second language acquisition (SLA) research.

## Coronal Stops

One area where ultrasound imaging feedback may prove useful is in training L1 English L2 Spanish learners to accurately perceive and produce /d t/ + /ɾ/ clusters. On the segmental level, Spanish and English both have the phonemes /t d/ in their phonological inventories, but they are realized phonetically differently. Spanish phrase-initial /t d/ are distinguished by short and lead lag, whereas English /t d/ are distinguished by long and short lag. With regards to place articulation, Spanish coronal stops are realized as dentals, whereas English ones are realized as alveolars. Previous research has looked at L2 Spanish acquisition of voice onset time [@casillas2020longitudinal], but there is a dearth when it comes to acquisition of place of articulation, possibly due to difficulties finding clear phonetic correlates for alveolar versus dental stops in these languages [@jongman1985acoustic; @dart1991articulatory]. Perceptually, American English speakers are able to distinguish dental versus alveolar stops in a different variety of English with only slightly less accuracy than natives of that variety [@kelly2019perception], indicating that accurate perception of Spanish coronal stop place of articulation is not impossible.

## Rhotics

With regards to [ɾ], Spanish and English differ in that /ɾ/ is a phoneme in the former, but an allophone of /t d/ in the latter. Spanish and English [ɾ] are realized phonetically similarly [@zue1979acoustic; @reetz2020phonetics], but the Spanish rhotics are typically supplanted by the English rhotic [ɹ] in the incipient stages of acquisition [@weech2009second], although the tap is more commonly produced in phonetic contexts that elicit its production in English [@olsen2012l2]. Target-like production increases with proficiency [@face2006intervocalic] and experience [@weech2009second], but @daidone2014quierro found that intermediate (fifth-semester undergraduates) and advanced learners (graduate students in a Hispanic linguistics and literature program or sixth-semester and above undergraduate students) distinguished the rhotics /r and ɾ/ with high accuracy in an AXB discrimination task, but concluded that they did not encode the distinction in their lexicon due to low rates of rejecting non-words where the rhotics were swapped (e.g., *[kiero] instead of [kieɾo] 'I want').

## Coronal Stop-Rhotic Clusters

In both Spanish and English, /t d/ + rhotic onset clusters are phonotactically allowed, but there are major phonetic differences between the two languages despite the individual segments of the cluster being relatively similar between the two languages, the resulting realization of the cluster proves to be quite distinct. In phrase-initial position, Spanish /tɾ dɾ/ have been acoustically described for evaluation of L2 production using three measures: stop voice onset time (VOT), rhotic manner (tap), rhotic duration and svarabhakti (epenthetical) vowel occurrence (and duration) [@gonzalez2023acquisition; @colantoni2006native; @morales2017development; @colantoni2018mixed]. However, notably absent is the place of articulation of the stop. This seems particularly important, as English /tr dr/ onset clusters are often pronounced as rhotacized post-alveolar affricates [@scobbie2006acquisition], starkly different from the Spanish dental stops and alveolar tap. Although there is disagreement on how to symbolically represent the English pronunciation [@schwartz2023all], it is agreed that there is affrication and that the rhotic is devoiced [@cruttenden2014gimson; @carley2019american]. Target-like production of the Spanish production does occur in advanced learners, but it is the exception [@colantoni2006native]. Relevant to the present study, @morales2017development found that learners who received visual feedback, in the form of spectrography training, outperformed a control group in stop-rhotic cluster production. The author concludes, in line with @colantoni2006native, that L1 English L2 Spanish learners acquire stop-rhotic cluster phonetic features in a specific order: voicing > rhotic duration > rhotic manner > epenthesis.

From an articulatory perspective, the last two stages of the development proposed by @morales2017development seem to align with a more target-like production of the stop consonants' place of articulation. That is, it is unlikely that an alveolar stop occurs with an alveolar tap due to the overlap in place of articulation, making it even more unlikely that the target-like epenthetic vowel will occur. Thus, it seems that participants who would most benefit from training specifically on stop-rhotic clusters would be learners who have already acquired target-like voicing contrasts and rhotic duration. However, training of place articulation with direct visual feedback through ultrasound imaging may provide insight into if the ordering proposed by @morales2017development is fixed or sensitive to training.

## Perception-Production Link

@van2015learning propose a link between perception and production, such that perception precedes production. As such, it may seem unintuitive to train learners on production before perception. @casillas2020phonetic corroborates the hypothesis that perception precedes production in a semi-longitudinal study of L1 English L2 Spanish learners acquiring voice onset time of stops. However, @sheldon1982acquisition finds that production can indeed precede perception in some cases, as is the case with L1 Japanese L2 English speakers acquiring liquid distinctions. As such, it cannot be given that perception always precedes production, nor that production cannot have an impact on perception, as is suggested in some L2 learning models [@swain2005output]. Furthermore, @catford1970auditory observed that learners given articulatory instruction, as opposed to simply listening and mimicking, performed better not only in production, but also perception. Based on these findings, production has been seen to hold a privileged position in L2 development, and training such, even without perception training, may result in gains for both production and perception.

# Present Study

The acquisition of coronal stop-rhotic clusters by L1 English L2 Spanish learners has received much attention [@gonzalez2023acquisition; @colantoni2006native; @morales2017development; @colantoni2018mixed], but training methodologies addressing learners' difficulties with this cluster remain far and few between. The current semi-longitudinal study presents a single-participant design [@gick2008ultrasound] to determine the impact of ultrasound training on production of coronal stop-rhotic clusters and to better understand the relationship between production and perception development.

# Method

## Participants

Twenty L1 English L2 Spanish learners participated in the study. Participants were enrolled in a six-week domestic immersion Spanish beginner program, where they had minimal contact with English. Before the program, they had minimal contact with Spanish. The twenty participants were split evenly into a control group and experimental group. Both groups completed the same tasks described below, but the experimental group received ultrasound training, whereas the control group did not.

## Tasks

Participants completed three tasks three times over the course of three weeks: a delayed shadowing task (production), an AXB discrimination task (perception), and an AB identification task (perception). All stimuli for the following tasks were recorded by an L1 English L1 Spanish simultaneous bilingual.

The delayed shadowing task consisted of 30 target nonce words and 40 distractors. All target words were bisyllabic trVCV with penultimate stress, the most common stress pattern in Spanish. Each of the five Spanish vowels /i e a o u/ represented the first V six times. The second syllable variably started with one of the six stop consonants /p t k b d g/, and the final V was always /a/. Stimuli were presented in random order and repeated three times each.

Both the AXB discrimination and AB identification tasks focused on two cues: voice onset time (VOT) and rhotic manner of articulation [@morales2017development]. The recorder of the stimuli produced each word, once using standard Spanish pronunciation, and once imitating a naive L1 English speaker to produce /tr dr/ as it would be produced in English. That is, as an affricate. To create two categories, the affricate was spliced into recordings with the standard Spanish pronunciation. Voice onset time was manipulated in `Praat` over seven steps, ranging from typical VOT for Spanish to typical VOT for English.

## Procedure

Data collection took place over the course of five sessions over five consecutive weeks, each session taking place on Sunday.

The control group, at each session, completed the delayed shadowing task, then the AXB discrimination task, and finally the AB identification task.

The experimental group likewise completed the same three tasks in the same order at each of the five sessions. However, during the middle three sessions, participants took part in ultrasound training. They always completed the production and perception tasks before the ultrasound training. Each training session took place over the course of approximately 30 to 45 minutes. Participants were shown how to use the ultrasound and instructed that they may view midsaggital or coronal views (the latter possibly being useful to view the English affricate). They were provided with .mp4 files of native Spanish speakers producing coronal stop-rhotic clusters, which included aligned audio and ultrasound imaging video. At each session, they were provided the following questions on a piece of paper that they answered [@olson2014benefits]: 1) Describe the visual difference between your production and the production by a native Spanish speaker. 2) Where is the Spanish speaker's tongue tip when they pronounce 't' or 't'? 3) Where is the Spanish speaker's tongue tip when they pronounce 'r'?

# Results

# Discussion

## Limitations and Future Directions

## Conclusion

# References

<!-- References will auto-populate in the refs div below -->

::: {#refs}
:::